on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn lint
      - name: "Generate test keys for JWT"
        run: |
          openssl genrsa -out private.pem 1024
          openssl rsa -in private.pem -pubout > public.pem
      - run: yarn test
